# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fc3689659dff238775fa2ce4b6895abab1fac0a852f2356c94c746893bce83f81252e28ac06d90b07e3def8c7b6c6ee96e04b9d0bfbf60640b6712f9e7d19b1

test:
  secret_key_base: 6f52afbfc871f8551d2f2f3fbf7dff4582098e3066d20b9c81808818a9b7d96cc269770e7b487f240e04f2835612474fd1ea9bb3bddabdf185023f3849bb937e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
